definitions:
  username.Token:
    properties:
      metadata:
        type: string
      owner:
        type: string
      targets:
        items:
          type: BlockchainAddress
        type: array
    type: object
info:
  contact: {}
  license: {}
  title: BNSAPI documentation
paths:
  /blocks/{blockHeight}:
    get:
      description: get block detail by blockHeight
      parameters:
      - description: Block Height
        in: path
        name: blockHeight
        required: true
        type: integer
      responses:
        "200": {}
        "404": {}
      summary: Get block details by height
      tags:
      - Status
  /cash/balances:
    get:
      description: The iov address may be in the bech32 (iov....) or hex (ON3LK...)
        format.
      parameters:
      - description: Bech32 or hex representation of an address
        in: path
        name: address
        type: string
      - description: Bech32 or hex representation of an address to be used as offset
        in: query
        name: offset
        type: string
      responses:
        "200": {}
        "404": {}
        "500": {}
      summary: returns balance in IOV Token of the given iov address
      tags:
      - IOV token
  /escrow/escrows:
    get:
      description: At most one of the query parameters must exist(excluding offset)
      parameters:
      - description: Iteration offset
        in: query
        name: offset
        type: string
      - description: Source address
        in: query
        name: source
        type: string
      - description: Destination address
        in: query
        name: destination
        type: string
      responses:
        "200": {}
        "400": {}
        "404": {}
        "500": {}
      summary: Returns a list of all the smart contract Escrows.
      tags:
      - IOV token
  /gconf/{extensionName}:
    get:
      parameters:
      - description: Extension name
        in: path
        name: extensionName
        required: true
        type: string
      responses:
        "200": {}
        "404": {}
        "500": {}
      summary: Get configuration with extension name
      tags:
      - Status
  /gov/proposals:
    get:
      description: At most one of the query parameters must exist(excluding offset)
      parameters:
      - description: Author address
        in: query
        name: author
        type: string
      - description: Base64 encoded electorate ID
        in: query
        name: electorate
        type: string
      - description: Base64 encoded Elector ID
        in: query
        name: elector
        type: string
      - description: Elector ID
        in: query
        name: electorID
        type: integer
      responses:
        "200": {}
        "400": {}
        "404": {}
        "500": {}
      summary: Returns a list of x/gov Votes entities.
      tags:
      - Governance
  /gov/votes:
    get:
      description: At most one of the query parameters must exist(excluding offset)
      parameters:
      - description: Base64 encoded Proposal ID
        in: query
        name: proposal
        type: string
      - description: Proposal ID
        in: query
        name: proposalID
        type: integer
      - description: Base64 encoded Elector ID
        in: query
        name: elector
        type: string
      - description: Elector ID
        in: query
        name: electorID
        type: integer
      responses:
        "200": {}
        "400": {}
        "404": {}
        "500": {}
      summary: Returns a list of Votes made on the governance.
      tags:
      - Governance
  /info/:
    get:
      responses:
        "200": {}
      summary: Returns information about this instance of `bnsapi`.
      tags:
      - Status
  /multisig/contracts:
    get:
      description: At most one of the query parameters must exist(excluding offset)
      parameters:
      - description: Iteration offset
        in: query
        name: offset
        type: string
      responses:
        "200": {}
        "404": {}
        "500": {}
      summary: Returns a list of all the multisig Contracts.
      tags:
      - IOV token
  /username/owner/{ownerAddress}:
    get:
      description: The iov address may be in the bech32 (iov....) or hex (ON3LK...)
        format.
      parameters:
      - description: Bech32 or hex representation of an address
        in: path
        name: ownerAddress
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/username.Token'
        "404": {}
        "500": {}
      summary: Returns the list of iov username (like bob*iov) owned by this iov address.
      tags:
      - Starname
  /username/resolve/{username}:
    get:
      parameters:
      - description: 'username. example: bob*iov'
        in: path
        name: username
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/username.Token'
        "404": {}
        "500": {}
      summary: Returns the username object with associated info for an iov username,
        like bob*iov
      tags:
      - Starname
swagger: "2.0"
