definitions:
  username.Token:
    properties:
      metadata:
        type: string
      owner:
        type: string
      targets:
        items:
          type: BlockchainAddress
        type: array
    type: object
info:
  contact: {}
  license: {}
  title: BNSAPI documentation
paths:
  /blocks/{blockHeight}:
    get:
      description: get block detail by blockHeight
      parameters:
      - description: Block Height
        in: path
        name: blockHeight
        required: true
        type: integer
      responses:
        "200": {}
        "404": {}
      summary: Get block details by height
  /cash/balances:
    get:
      parameters:
      - description: Bech32 or hex representation of an address
        in: path
        name: address
        type: string
      - description: Bech32 or hex representation of an address to be used as offset
        in: query
        name: offset
        type: string
      responses:
        "200": {}
        "404": {}
        "500": {}
      summary: returns balances based on iov address
  /escrow/escrows:
    get:
      description: At most one of the query parameters must exist(excluding offset)
      parameters:
      - description: Iteration offset
        in: query
        name: offset
        type: string
      - description: Source address
        in: query
        name: source
        type: string
      - description: Destination address
        in: query
        name: destination
        type: string
      responses:
        "200": {}
        "400": {}
        "404": {}
        "500": {}
      summary: Returns a list of x/escrow Escrow entities.
  /gconf/{extensionName}:
    get:
      parameters:
      - description: Extension name
        in: path
        name: extensionName
        required: true
        type: string
      responses:
        "200": {}
        "404": {}
        "500": {}
      summary: Get configuration with extension name
  /info/:
    get:
      responses:
        "200": {}
      summary: Returns information about this instance of `bnsapi`.
  /multisig/contracts:
    get:
      description: At most one of the query parameters must exist(excluding offset)
      parameters:
      - description: Iteration offset
        in: query
        name: offset
        type: string
      responses:
        "200": {}
        "404": {}
        "500": {}
      summary: Returns a list of multisig Contract entities.
  /username/owner/{ownerAddress}:
    get:
      parameters:
      - description: Bech32 or hex representation of an address
        in: path
        name: ownerAddress
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/username.Token'
        "404": {}
        "500": {}
      summary: Returns the list of iov starname owned by this iov address
  /username/resolve/{username}:
    get:
      parameters:
      - description: 'username. example: bob*iov'
        in: path
        name: username
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/username.Token'
        "404": {}
        "500": {}
      summary: Returns balances based on iov address.
swagger: "2.0"
